[Design] POStringLocalizer
aspnet/Localization pull request #309
Opened 2016-12-14 23:32 UTC by ryanbrandenburg

This is a design PR for the POStringLocalizer work. Missing from the is the pluralization work (other than just to parse the file) because we haven't decided on what the shape of IPluralizedStringLocalizer is.

2016-12-15 00:02 UTC, hishamco commented
Finally we have it 😄 , great job @ryanbrandenburg I appreciate it.
One thing why we didn't finalize the pluralization stuff after that build this on top of that, as we know PO files support pluralization by its nature

2016-12-15 15:51 UTC, hishamco commented
@ryanbrandenburg can you fix the checks failure?

2016-12-16 01:13 UTC, hishamco requested changes

2016-12-16 01:13 UTC, hishamco commented on src/Microsoft.Extensions.Localization/Internal/POLines/ContextLine.cs
> +        public override string Token
```csharp
public override string Token => "msgctxt ";
```

2016-12-16 01:13 UTC, hishamco commented on src/Microsoft.Extensions.Localization/Internal/POLines/ContextLine.cs
> +        public override Line Parse(string value)
```csharp
public override Line Parse(string value) =>
    new ContextLine
    {
        Value = TrimToken(new StringBuilder(value))
    };
```

2016-12-16 01:13 UTC, hishamco commented on src/Microsoft.Extensions.Localization/Internal/POLines/FlagLine.cs
> +        public override string Token
```csharp
public override string Token => "#, ";
```

2016-12-16 01:13 UTC, hishamco commented on src/Microsoft.Extensions.Localization/Internal/POLines/FlagLine.cs
> +        public override Line Parse(string value)
```csharp
public override Line Parse(string value) =>
    new FlagLine
    {
        Value = TrimToken(new StringBuilder(value)).ToString().Split(',').ToList()
    };
```

2016-12-16 01:13 UTC, hishamco commented on src/Microsoft.Extensions.Localization/Internal/POLines/Line.cs
> +        private bool IsQuote(char character)
```csharp
private bool IsQuote(char character) =>
    character == '"' || character == '\'';
```

2016-12-16 01:13 UTC, hishamco commented on src/Microsoft.Extensions.Localization/Internal/POLines/Line.cs
> +        private StringBuilder Unescape(StringBuilder value)
```csharp
private StringBuilder Unescape(StringBuilder value) =>
    value.Replace("\\\"", "\"").Replace("\\'", "'");
```

2016-12-16 01:13 UTC, hishamco commented on src/Microsoft.Extensions.Localization/Internal/POLines/LiteralLine.cs
> +        public override Line Parse(string value)
```csharp
public override Line Parse(string value) =>
    new LiteralLine
    {
        Value = TrimQuotes(new StringBuilder(value))
    };
```

2016-12-16 01:21 UTC, hishamco commented
@ryanbrandenburg It will be nice if `POLocalizer` implement `IPluralizeStringLocalizer` that I suggest in PR #305 instead of `IStringLocalizer` because it doesn't support pluralization, so that's why you need to do it yourself in each implementation that may support pluralization. My aim to eliminate the tedious and repetitive code that we wrote in such cases.

Second thing the amount of code to parse PO is too much, can we simplify this like what we did in INI configuration as example?

2017-04-04 18:38 UTC, closed without merging

2017-04-05 07:08 UTC, hishamco commented
@sebastienros is that mean that `POStringLocalizer` will not be supported?!!

2017-04-05 07:16 UTC, sebastienros commented
Fortunately no. It's just that this branch required more changes so it will be started fresh.

2017-04-05 07:23 UTC, hishamco commented
I see, furthermore I saw that implementation is complicated little bit, It would be nice if we can simplify parsing like what I have seen in INI Configuration

thanks